[package]
name = "rfetch"
version = "0.1.0"
authors = ["icebox246 <iceboxpoczta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
libc = "0.2"
